<?xml version="1.0" ?>
<robot name="vacuum_robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/lidar.urdf.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/depth.urdf.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/imu.urdf.xacro"/>
    
    <xacro:property name="chassis_radius" value="0.2"/> <!-- Радиус корпуса -->
    <xacro:property name="chassis_height" value="0.1"/> <!-- Высота корпуса -->
    <xacro:property name="wheel_radius" value="0.05"/>
    <xacro:property name="wheel_thickness" value="0.03"/>
    <xacro:property name="wheel_mass" value="0.2"/>
    <xacro:property name="wheel_offset_x" value="0.2"/>
    <xacro:property name="wheel_offset_y" value="0.15"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.02"/>
    <xacro:property name="caster_wheel_mass" value="0.05"/>
    <xacro:property name="caster_wheel_offset_x" value="0.1"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>
    <xacro:property name="mass" value="1.5"/> <!-- Масса корпуса -->

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="gray">
        <color rgba="0.7 0.7 0.7 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <link name="base_link">
    </link>

    <link name="base_footprint">
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 -0.1" rpy="0 0 0"/>
    </joint>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <inertial>
            <origin xyz="0 0 ${chassis_height / 2}" rpy="0 0 0"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/2) * mass * (chassis_radius * chassis_radius)}" 
                     ixy="0.0" ixz="0.0"
                     iyy="${(1/2) * mass * (chassis_radius * chassis_radius)}" 
                     iyz="0.0"
                     izz="${(1/2) * mass * (chassis_radius * chassis_radius)}" />
        </inertial>
        <visual>
            <origin xyz="0 0 ${chassis_height / 2}"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/> <!-- Цилиндр для корпуса -->
            </geometry>
            <material name="gray"/>
        </visual>
        <collision>
            <origin xyz="0 0 ${chassis_height / 2}"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/> <!-- Цилиндр для коллизий -->
            </geometry>
        </collision>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Gray</material>
    </gazebo>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" 
                     ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" 
                     iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${wheel_mass}" />
            <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" 
                     ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" 
                     iyz="0.0"
                     izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- Caster Wheel -->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${caster_wheel_mass}" />
            <inertia ixx="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" 
                     ixy="0.0" ixz="0.0"
                     iyy="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" 
                     iyz="0.0"
                     izz="${(2/5) * caster_wheel_mass * (caster_wheel_radius*caster_wheel_radius)}" />
        </inertial>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!-- Blade -->
    <joint name="blade_joint" type="fixed">
        <parent link="chassis"/>
        <child link="blade"/>
        <origin xyz="0 0 ${chassis_height + 0.02}"/>
    </joint>

    <link name="blade">
        <visual>
            <geometry>
                <box size="0.1 0.01 0.005"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.01 0.005"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="0.1"/>
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001"/>
        </inertial>
    </link>

    <gazebo reference="blade">
        <material>Gazebo/Black</material>
    </gazebo>

</robot>